DROP TABLE IF EXISTS PRODUCTS, CUSTOMERS, STORES, SUPPLIERS, FACT_TABLE, DATES;

CREATE TABLE PRODUCTS (`PRODUCT_ID` VARCHAR(100) NOT NULL, `PRODUCT_NAME` VARCHAR(100) NOT NULL,
`PRICE` DOUBLE NOT NULL, CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID));

CREATE TABLE CUSTOMERS (`CUSTOMER_ID` VARCHAR(100) NOT NULL, `CUSTOMER_NAME` VARCHAR(100) NOT NULL,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE STORES (`STORE_ID` VARCHAR(100) NOT NULL, `STORE_NAME` VARCHAR(100) NOT NULL, 
CONSTRAINT STORE_PK PRIMARY KEY (STORE_ID));

CREATE TABLE SUPPLIERS (`SUPPLIERS_ID` VARCHAR(100) NOT NULL, `SUPPLIERS_NAME` VARCHAR(100) NOT NULL, 
CONSTRAINT SUPPLIERS_PK PRIMARY KEY (SUPPLIERS_ID));
 
 CREATE TABLE DATES (`DATE_ID` VARCHAR(100) NOT NULL, `DAY` VARCHAR(100) NOT NULL,
 `WEEK` VARCHAR(100) NOT NULL,`MONTH` VARCHAR(100) NOT NULL,
 `QUATER` VARCHAR(100) NOT NULL,`YEAR` VARCHAR(100) NOT NULL,
 CONSTRAINT DATE_PK PRIMARY KEY (DATE_ID)); 
 
CREATE TABLE FACT_TABLE (`TRANSACTION_ID` VARCHAR(100) PRIMARY KEY, `PRODUCT_ID` VARCHAR(100) ,
 `CUSTOMER_ID` VARCHAR(100) , `SUPPLIERS_ID` VARCHAR(100) ,
 `STORE_ID` VARCHAR(100) , `QUANTITY` VARCHAR(100) NOT NULL, `SUM` DOUBLE, `DATE_ID` VARCHAR(100) NOT NULL,
 FOREIGN KEY (DATE_ID) REFERENCES DATES(DATE_ID),
 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID), 
 FOREIGN KEY (SUPPLIERS_ID) REFERENCES SUPPLIERS(SUPPLIERS_ID), FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID));
 
 

 